name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case
      placeholder: Explain how this feature would be used and why it's important.
    validations:
      required: true

  - type: textarea
    id: example-config
    attributes:
      label: Example Configuration
      description: If applicable, show how the feature would work in configuration
      render: javascript
      placeholder: |
        // eslint.config.js
        const eslintConfigKubit = require('eslint-config-kubit');

        module.exports = eslintConfigKubit({
          newFeature: {
            // example configuration
          }
        });

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      options:
        - label: New ESLint rule
        - label: New configuration option
        - label: Performance improvement
        - label: Developer experience improvement
        - label: Documentation improvement
        - label: Other

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
